@startuml

title Диаграмма контейнеров банка "Стандарт"

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(Client, "Клиент банка")
Person(FOManager, "Менеджер Фронт-офиса")
Person(BODepositManager, "Менеджер Бэк-офиса по депозитам")
Person(BOCreditManager, "Менеджер Бэк-офиса по кредитам")
Person(CallOperator, "Оператор кол-центра")

Container_Boundary(Bank, "Банк Стандарт") {
    Container(Site, "Сайт")
    Container(InternetBank, "Интернет банк")
    Container(FECallCenter, "Frontend кол-центра")
    Container(FEAbs, "Frontend АБС")
    Container(ApiGateway, "Api Gateway", "Шлюз для направления запросов на соответствующие сервисы")
    Container(BESite, "Backend сайта и интернет банка")
    Container(BECallCenter, "Backend кол-центра")
    Container(BEAbs, "Backend АБС")
    Container(NotificationService, "Сервис нотификаций")
    Container(SMSGateway, "CМС Шлюз")
    ContainerDb(CacheInfo, "Кэш справочной информации", "Redis")
    ContainerDb(DBAbs, "БД АБС", "Oracle", "Хранит данные о заявках, ставках, бухгалтерии")
    ContainerDb(DBCall, "БД Кол-центра", "PostgreSQL", "Хранит данные о заявках")
    ContainerDb(DBClient, "БД сайта и интернет-банка", "PostgreSQL", "Хранит данные о клиентах и депозитах, справочную информацию")
    Container(ReplicationService, "Сервис репликации данных")
    ContainerQueue(Queue, "Брокер сообщений", "Обмен данными между сервисами")
}

System_Ext(Telecom, "Телеком-оператор")

Rel(Client, FOManager, "Подает заявку")
Rel(Client, Site, "Смотрит информацию о банке и доступные депозиты, подает заявку")
Rel(Client, InternetBank, "Смотрит информацию о банке, доступные депозиты, персонализированные ставки, подает заявку")
Rel(CallOperator, FECallCenter, "Обрабатывает заявку")
Rel(CallOperator, Client, "Предлагает особые условия, приглашает прийти в отделение для идентификации")
Rel(FOManager, FEAbs, "Запрашивает ставку, размещает маркетинговую информацию, создает депозит, загружает документы")
Rel(BODepositManager, FEAbs, "Обрабатывает заявки, определяет ставку")
Rel(BOCreditManager, FEAbs, "Анализирует уровень кредитного риска относительно клиентов")
Rel(Site, ApiGateway, "Отправляет запросы")
Rel(InternetBank, ApiGateway, "Отправляет запросы")
Rel(FECallCenter, ApiGateway, "Отправляет запросы")
Rel(FEAbs, ApiGateway, "Отправляет запросы")
Rel(ApiGateway, BESite, "Отправляет запросы")
Rel(ApiGateway, BECallCenter, "Отправляет запросы")
Rel(ApiGateway, BEAbs, "Отправляет запросы")
Rel(BESite, CacheInfo, "Работает с кэшем")
Rel(BESite, DBCall, "Записывает заявки")
Rel(BECallCenter, DBCall, "Читает данные")
Rel(BESite, DBClient, "Читает, записывает данные")
Rel(BEAbs, DBAbs, "Читает, записывает данные")
Rel(BEAbs, Queue, "Публикует уведомления")
Rel(NotificationService, Queue, "Получает уведомления")
Rel(ReplicationService, DBAbs, "Реплицирует данные")
Rel(ReplicationService, DBCall, "Реплицирует данные")
Rel(NotificationService, SMSGateway, "Отправляет СМС с решением по депозиту")
Rel(SMSGateway, Telecom, "Отправляет СМС")
Rel(Telecom, Client, "Отправляет СМС")

@enduml